name: Basic Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CodeChecks:
    name: Basic code checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y clang-format-15

    - name: Check C/C++ code formatting
      run: |
        find . -name "*.cpp" -o -name "*.h" | xargs clang-format-15 --dry-run --Werror